// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: order.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	List          []*OrderItem           `protobuf:"bytes,4,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAddReq) Reset() {
	*x = OrderAddReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAddReq) ProtoMessage() {}

func (x *OrderAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAddReq.ProtoReflect.Descriptor instead.
func (*OrderAddReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderAddReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *OrderAddReq) GetList() []*OrderItem {
	if x != nil {
		return x.List
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`   // 商品ID
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // 购买数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"` // 订单编号
	Total         float32                `protobuf:"fixed32,2,opt,name=total,proto3" json:"total,omitempty"`   // 订单总金额
	PayUrl        string                 `protobuf:"bytes,3,opt,name=payUrl,proto3" json:"payUrl,omitempty"`   // 支付链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAddResp) Reset() {
	*x = OrderAddResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAddResp) ProtoMessage() {}

func (x *OrderAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAddResp.ProtoReflect.Descriptor instead.
func (*OrderAddResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderAddResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderAddResp) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderAddResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

type NotifyPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPayReq) Reset() {
	*x = NotifyPayReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPayReq) ProtoMessage() {}

func (x *NotifyPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPayReq.ProtoReflect.Descriptor instead.
func (*NotifyPayReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

// 创建订单响应
type NotifyPayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPayResp) Reset() {
	*x = NotifyPayResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPayResp) ProtoMessage() {}

func (x *NotifyPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPayResp.ProtoReflect.Descriptor instead.
func (*NotifyPayResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05proto\"K\n" +
	"\vOrderAddReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12$\n" +
	"\x04List\x18\x04 \x03(\v2\x10.proto.OrderItemR\x04List\"A\n" +
	"\tOrderItem\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\x03R\agoodsId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"V\n" +
	"\fOrderAddResp\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x02R\x05total\x12\x16\n" +
	"\x06payUrl\x18\x03 \x01(\tR\x06payUrl\"\x0e\n" +
	"\fNotifyPayReq\"\x0f\n" +
	"\rNotifyPayResp2t\n" +
	"\x05Order\x123\n" +
	"\bOrderAdd\x12\x12.proto.OrderAddReq\x1a\x13.proto.OrderAddResp\x126\n" +
	"\tNotifyPay\x12\x13.proto.NotifyPayReq\x1a\x14.proto.NotifyPayRespB\x04Z\x02./b\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_order_proto_goTypes = []any{
	(*OrderAddReq)(nil),   // 0: proto.OrderAddReq
	(*OrderItem)(nil),     // 1: proto.OrderItem
	(*OrderAddResp)(nil),  // 2: proto.OrderAddResp
	(*NotifyPayReq)(nil),  // 3: proto.NotifyPayReq
	(*NotifyPayResp)(nil), // 4: proto.NotifyPayResp
}
var file_order_proto_depIdxs = []int32{
	1, // 0: proto.OrderAddReq.List:type_name -> proto.OrderItem
	0, // 1: proto.Order.OrderAdd:input_type -> proto.OrderAddReq
	3, // 2: proto.Order.NotifyPay:input_type -> proto.NotifyPayReq
	2, // 3: proto.Order.OrderAdd:output_type -> proto.OrderAddResp
	4, // 4: proto.Order.NotifyPay:output_type -> proto.NotifyPayResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
